import React, { useState } from 'react';
import { Calculator, Search, HelpCircle, ArrowRight } from 'lucide-react';

interface BeginnerFormula {
  id: string;
  name: string;
  formula: string;
  meaning: string;
  example: string;
  category: string;
}

const BEGINNER_FORMULAS: BeginnerFormula[] = [
  {
    id: 'f-risk-amount',
    name: 'Risk Amount',
    formula: 'Risk Amount = Account Equity × (Risk % / 100)',
    meaning: 'The exact monetary capital you are willing to lose if your trade hits its stop loss.',
    example: 'Account = ₹1,00,000. Risk % = 1%. Risk Amount = ₹1,00,000 × 0.01 = ₹1,000.',
    category: 'Risk Management'
  },
  {
    id: 'f-rr-ratio',
    name: 'Risk-to-Reward Ratio (R:R)',
    formula: 'R:R = (Entry Price - Stop Loss) : (Take Profit - Entry Price)',
    meaning: 'The ratio between your potential downside loss and your planned upside profit target.',
    example: 'Risking $2 to make $6 gives an R:R of 1:3. You make 3x what you risk.',
    category: 'Risk Management'
  },
  {
    id: 'f-pos-size',
    name: 'Basic Position Size',
    formula: 'Shares/Units = Risk Budget / |Entry Price - Stop Loss Price|',
    meaning: 'Determines the exact lot or share size so that your maximum loss never exceeds your risk budget.',
    example: 'Risk budget = $200. Entry = $50, Stop = $48 (difference = $2). Units = $200 / $2 = 100 shares.',
    category: 'Execution'
  },
  {
    id: 'f-pnl',
    name: 'Profit / Loss (P&L)',
    formula: 'P&L = Quantity × (Exit Price - Entry Price)',
    meaning: 'The raw financial return generated by closing an open position.',
    example: 'Bought 50 shares at $120, sold at $130. P&L = 50 × ($130 - $120) = $500 profit.',
    category: 'Trading Basics'
  },
  {
    id: 'f-pct-change',
    name: 'Percentage Change',
    formula: '% Change = ((New Price - Old Price) / Old Price) × 100',
    meaning: 'The relative price movement of an asset expressed as a percentage of its starting price.',
    example: 'A stock rises from $200 to $230. % Change = ((230 - 200) / 200) × 100 = (30 / 200) × 100 = +15%.',
    category: 'Trading Basics'
  },
  {
    id: 'f-win-rate',
    name: 'Win Rate',
    formula: 'Win Rate % = (Winning Trades / Total Closed Trades) × 100',
    meaning: 'The percentage of trades that close with positive net profit.',
    example: 'Out of 20 trades, 12 were profitable. Win Rate = (12 / 20) × 100 = 60%.',
    category: 'Performance'
  },
  {
    id: 'f-avg-win',
    name: 'Average Win',
    formula: 'Average Win = Total Gross Profits / Number of Winning Trades',
    meaning: 'The typical monetary return you capture on your winning setups.',
    example: 'Total profits of $3,000 across 6 winning trades. Average Win = $3,000 / 6 = $500.',
    category: 'Performance'
  },
  {
    id: 'f-avg-loss',
    name: 'Average Loss',
    formula: 'Average Loss = Total Gross Losses / Number of Losing Trades',
    meaning: 'The typical monetary loss incurred when a trade does not work out.',
    example: 'Total losses of $1,200 across 4 losing trades. Average Loss = $1,200 / 4 = $300.',
    category: 'Performance'
  },
  {
    id: 'f-expectancy',
    name: 'Expectancy (Basic Introduction)',
    formula: 'Expectancy = (Win Rate × Avg Win) - (Loss Rate × Avg Loss)',
    meaning: 'The expected average profit or loss per trade over a statistically significant sample of trades.',
    example: 'Win Rate 50% ($500 win), Loss Rate 50% ($250 loss). Expectancy = (0.50 × 500) - (0.50 × 250) = 250 - 125 = +$125 per trade.',
    category: 'Quantitative Basics'
  }
];

export const NormalFormulaSheet: React.FC = () => {
  const [searchTerm, setSearchTerm] = useState('');

  const filteredFormulas = BEGINNER_FORMULAS.filter(f =>
    f.name.toLowerCase().includes(searchTerm.toLowerCase()) ||
    f.category.toLowerCase().includes(searchTerm.toLowerCase()) ||
    f.formula.toLowerCase().includes(searchTerm.toLowerCase())
  );

  return (
    <div id="normal-formula-sheet" className="space-y-6">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 p-5 rounded-2xl bg-white dark:bg-slate-850 border border-slate-200 dark:border-slate-800 shadow-xs">
        <div>
          <div className="flex items-center gap-2">
            <div className="w-8 h-8 rounded-xl bg-indigo-100 dark:bg-indigo-900/50 flex items-center justify-center text-indigo-600 dark:text-indigo-400">
              <Calculator className="w-4 h-4" />
            </div>
            <h3 className="text-base sm:text-lg font-black text-slate-900 dark:text-white">
              Beginner Formula Sheet
            </h3>
          </div>
          <p className="text-xs text-slate-500 dark:text-slate-400 mt-1">
            Essential mathematical relationships for risk control, performance analysis, and capital protection.
          </p>
        </div>

        {/* Search */}
        <div className="relative w-full sm:w-72">
          <Search className="w-4 h-4 text-slate-400 absolute left-3 top-1/2 -translate-y-1/2" />
          <input
            type="text"
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            placeholder="Search formulas or terms..."
            className="w-full pl-9 pr-3 py-2 rounded-xl bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 text-xs text-slate-900 dark:text-white placeholder-slate-400 focus:outline-hidden focus:ring-2 focus:ring-blue-500"
          />
        </div>
      </div>

      {/* Grid of Formulas */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {filteredFormulas.map((item) => (
          <div
            key={item.id}
            className="p-5 rounded-2xl bg-white dark:bg-slate-850 border border-slate-200 dark:border-slate-800 shadow-xs space-y-3 flex flex-col justify-between"
          >
            <div className="space-y-2">
              <div className="flex items-center justify-between">
                <span className="px-2.5 py-0.5 rounded-md text-[10px] font-bold bg-indigo-50 dark:bg-indigo-950/60 text-indigo-700 dark:text-indigo-300">
                  {item.category}
                </span>
              </div>

              <h4 className="text-sm sm:text-base font-bold text-slate-900 dark:text-white">
                {item.name}
              </h4>

              {/* Formula display */}
              <div className="p-3 rounded-xl bg-slate-900 dark:bg-black text-emerald-400 font-mono text-xs sm:text-sm font-semibold border border-slate-800 shadow-inner">
                {item.formula}
              </div>

              {/* Meaning */}
              <div className="text-xs text-slate-600 dark:text-slate-300">
                <strong className="text-slate-900 dark:text-white">Meaning: </strong>
                {item.meaning}
              </div>
            </div>

            {/* Example */}
            <div className="p-3 rounded-xl bg-slate-50 dark:bg-slate-800/60 border border-slate-200/60 dark:border-slate-700/60 text-xs text-slate-700 dark:text-slate-300">
              <span className="font-bold text-indigo-600 dark:text-indigo-400 block mb-0.5">
                Real-World Example:
              </span>
              {item.example}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};
